# OpenVox — Homebrew formula for the `amznsri/openvox` tap.
#
# Tap location after publish:
#   https://github.com/amznsri/homebrew-openvox/blob/main/Formula/openvox.rb
#
# Install path for users:
#   brew tap amznsri/openvox
#   brew install openvox
#
# This file is the source of truth in the OpenVox repo. CI copies it
# (with version + sha256 substitutions from the release tag) to the
# tap repo on every tagged release — see .github/workflows/release.yml
# in Phase 4 PR-5.
#
# REGENERATING THE RESOURCE BLOCKS
# ---------------------------------
# Every Python dependency in pyproject.toml needs a `resource` block
# below with a non-empty sha256. The release pipeline regenerates the
# whole block on every tag — you generally don't touch this file by
# hand. To regenerate locally for inspection:
#
#   python -m venv /tmp/openvox-resgen
#   /tmp/openvox-resgen/bin/python -m pip install --upgrade pip
#   /tmp/openvox-resgen/bin/python scripts/gen_homebrew_resources.py \
#       openvox-core==<latest version> > /tmp/resources.rb
#   # Paste /tmp/resources.rb between the BEGIN/END markers below.
#
# We previously used `homebrew-pypi-poet`; it's broken for OpenVox (see
# the script docstring for the two failure modes). The new generator
# uses pip's `--dry-run --report` to resolve the pinned dep set, then
# picks an OS-portable artefact per dep — sdist when available,
# universal `py3-none-any.whl` otherwise, per-OS wheels (in
# `on_macos`/`on_linux` blocks) when neither exists. The output between
# BEGIN/END below may therefore include both top-level `resource`
# blocks and platform-guarded ones — that's expected.
#
# Until the first PyPI release, this formula is a SCAFFOLD — the
# resource list below is intentionally empty. The release-pipeline
# workflow generates the full list automatically as part of the
# publish step.

class Openvox < Formula
  include Language::Python::Virtualenv

  desc "Local-first, open-source voice agent platform"
  homepage "https://github.com/amznsri/openvox"

  # These two lines are rewritten by the release pipeline on every tag.
  # The 0.0.0 + zero-sha placeholders are intentional — they make a
  # mistakenly-tapped pre-release formula fail at the download step
  # rather than silently install a broken build.
  url "https://files.pythonhosted.org/packages/source/o/openvox-core/openvox_core-0.0.0.tar.gz"
  version "0.0.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  license "Apache-2.0"
  head "https://github.com/amznsri/openvox.git", branch: "main"

  # Build-time deps come first (brew style enforces alphabetical
  # ordering, but `build`-tagged deps generally lead). With wheel-first
  # resources we don't actually compile the heavy stuff
  # (numpy/cryptography/etc. — those are pre-built per OS). A handful
  # of sdist-only deps (bcrypt declares pkgconf + rust in its PyPI
  # metadata) still need a build toolchain.
  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  depends_on "ffmpeg"             # used by pydub for audio decoding
  depends_on "python@3.12"        # ≥ 3.11 per pyproject; tap defaults to .12

  # ─── BEGIN GENERATED RESOURCES (regenerated by release pipeline) ───
  # Intentionally empty until the first PyPI release. See header.
  # ─── END GENERATED RESOURCES ───

  def install
    # Why we don't use `virtualenv_install_with_resources` (the
    # Homebrew-blessed one-liner): it hardcodes `pip install
    # --no-binary :all:` which forbids wheel resources and forces
    # every dep to compile from source. With ~17 compiled deps in
    # the tree (numpy / cryptography / pydantic-core / asyncpg /
    # aiohttp / hiredis / etc.) that's 20-40 min on M-series and
    # can hard-fail if Homebrew didn't pre-install Fortran/BLAS.
    #
    # Custom path: create the venv, then pip-install each resource
    # individually. Wheel resources go in via `pip install <whl-file>`;
    # sdist resources go in via the standard stage-then-`pip install .`.
    # Build-isolation stays ON so sdists that need setuptools /
    # hatchling pick up their build backend from PyPI at install
    # time (default pip behaviour, no flag needed).
    # `opt_libexec/bin/python` (no version suffix) is the PEP-668-
    # friendly framework wrapper for python@3.12 — the one Homebrew's
    # own Virtualenv helper uses internally. Using the explicit path
    # (rather than the formula name "python@3.12" or even the
    # executable name "python3.12") avoids any PATH-resolution
    # surprise during `brew install`: the v0.2.3 form
    # `virtualenv_create(libexec, "python@3.12")` blew up because
    # brew tried to invoke `python@3.12` as a binary — that's a
    # FORMULA name, not an executable name.
    parent_python = Formula["python@3.12"].opt_libexec/"bin/python"
    venv_python = libexec/"bin/python"

    # virtualenv_create populates libexec/ with the venv. We don't keep
    # a handle on the returned Virtualenv object because we install
    # resources directly via pip below — its helper methods would
    # re-introduce --no-binary :all:.
    virtualenv_create(libexec, parent_python.to_s)

    install_into_venv = lambda do |target|
      system parent_python, "-m", "pip",
             "--python=#{venv_python}",
             "install",
             "--no-deps",
             "--disable-pip-version-check",
             target.to_s
    end

    resources.each do |r|
      if r.url.end_with?(".whl")
        # Wheel: brew's standard `r.stage` block unpacks the wheel
        # into a dir (wheels are zips); pip then refuses the dir
        # because of --no-binary :all: in its build path. Skip
        # stage and install directly from the cached download.
        r.fetch
        install_into_venv.call(r.cached_download)
      else
        # Sdist: standard stage and install.
        r.stage do
          install_into_venv.call(Pathname.pwd)
        end
      end
    end

    # openvox-core itself comes from the formula's main `url`
    # (an sdist). buildpath is the unpacked tree root.
    install_into_venv.call(buildpath)

    # Expose the bin shim on PATH.
    bin.install_symlink Dir[libexec/"bin/openvox"]
  end

  test do
    # Sanity check after install — verifies the bin works without
    # crashing. We don't start the server here because that would
    # require network + open a port on the build machine.
    assert_match version.to_s, shell_output("#{bin}/openvox version")
    assert_match "openvox", shell_output("#{bin}/openvox --help")
  end
end
