# OpenVox — Homebrew formula for the `amznsri/openvox` tap.
#
# Tap location after publish:
#   https://github.com/amznsri/homebrew-openvox/blob/main/Formula/openvox.rb
#
# Install path for users:
#   brew tap amznsri/openvox
#   brew install openvox
#
# This file is the source of truth in the OpenVox repo. CI copies it
# (with version + sha256 substitutions from the release tag) to the
# tap repo on every tagged release — see .github/workflows/release.yml
# in Phase 4 PR-5.
#
# REGENERATING THE RESOURCE BLOCKS
# ---------------------------------
# Every Python dependency in pyproject.toml needs a `resource` block
# below with a non-empty sha256. The release pipeline regenerates the
# whole block on every tag — you generally don't touch this file by
# hand. To regenerate locally for inspection:
#
#   python -m venv /tmp/openvox-resgen
#   /tmp/openvox-resgen/bin/python -m pip install --upgrade pip
#   /tmp/openvox-resgen/bin/python scripts/gen_homebrew_resources.py \
#       openvox-core==<latest version> > /tmp/resources.rb
#   # Paste /tmp/resources.rb between the BEGIN/END markers below.
#
# We previously used `homebrew-pypi-poet`; it's broken for OpenVox (see
# the script docstring for the two failure modes). The new generator
# uses pip's `--dry-run --report` to resolve the pinned dep set, then
# picks an OS-portable artefact per dep — sdist when available,
# universal `py3-none-any.whl` otherwise, per-OS wheels (in
# `on_macos`/`on_linux` blocks) when neither exists. The output between
# BEGIN/END below may therefore include both top-level `resource`
# blocks and platform-guarded ones — that's expected.
#
# Until the first PyPI release, this formula is a SCAFFOLD — the
# resource list below is intentionally empty. The release-pipeline
# workflow generates the full list automatically as part of the
# publish step.

class Openvox < Formula
  include Language::Python::Virtualenv

  desc "Local-first, open-source voice agent platform"
  homepage "https://github.com/amznsri/openvox"

  # These two lines are rewritten by the release pipeline on every tag.
  # The 0.0.0 + zero-sha placeholders are intentional — they make a
  # mistakenly-tapped pre-release formula fail at the download step
  # rather than silently install a broken build.
  url "https://files.pythonhosted.org/packages/source/o/openvox-core/openvox_core-0.0.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  version "0.0.0"

  license "Apache-2.0"
  head "https://github.com/amznsri/openvox.git", branch: "main"

  depends_on "ffmpeg"          # used by pydub for audio decoding
  depends_on "python@3.12"     # ≥ 3.11 per pyproject; tap defaults to .12
  depends_on "rust" => :build  # needed by some sub-deps (cryptography wheels usually ship pre-built but we cover the source-build path)

  # ─── BEGIN GENERATED RESOURCES (regenerated by release pipeline) ───
  # Intentionally empty until the first PyPI release. See header.
  # ─── END GENERATED RESOURCES ───

  def install
    # `virtualenv_install_with_resources` is the Homebrew-blessed
    # one-liner that creates a venv, installs every `resource` above,
    # then installs the main package. Handles bin-shim creation +
    # rpath fixups so `brew install openvox` produces a clean
    # `openvox` on PATH.
    virtualenv_install_with_resources
  end

  test do
    # Sanity check after install — verifies the bin works without
    # crashing. We don't start the server here because that would
    # require network + open a port on the build machine.
    assert_match version.to_s, shell_output("#{bin}/openvox version")
    assert_match "openvox", shell_output("#{bin}/openvox --help")
  end
end
